### ISSUE TITLE
DTXMania NX crashes when CLASSIC is enabled in Config.ini

### ISSUE THREAD

**Issue by Villadelfia** [limyz/DTXmaniaNX#108] opened 2021-05-28 18:29 UTC
Steps to reproduce:
Set CLASSIC=1 in Config.ini.

Expected behavior:
The game does not crash.

Observed behavior:
The game crashes when you scroll onto the <Random Song> field in the song wheel and when you enter a folder and start scrolling.

**Comment by limyz** [comment] 2021-06-20 10:20
Fixed in #109

**Comment by limyz** [comment] 2021-12-10 06:17
See #113

**Comment by fisyher** [comment] 2021-12-11 14:45
Fixed with a proper null check instead of using null-conditional operators, which is hard to read and should be avoided

**Closed by fisyher** 2021-12-11 14:45 UTC
Labels: bug

**Comment by jaredmorgs** [comment] 2021-12-30 22:47
Hah, so that is what was causing the game to crash. 

I encountered this bug plenty of times but was unsure why the issue was happening, so thanks for tracking down the root cause @Villadelfia. 

The only way I could resolve this was to rename my config and then have DTXMania re-create the config file again.
Then I had to reset all the settings from scratch because I didn't know which one caused the issue.

The exception error the app threw didn't really help me work out what the problem was as an end-user either, so this was a frustrating bug.

Thank you very much to all for tracking down the cause of the bug. 👍🏻
